<ul id="dropmenu1" class="dropMenu">
  
</ul><ul id="dropmenu2" class="dropMenu">
  
</ul><ul id="dropmenu3" class="dropMenu">
  
</ul><ul id="dropmenu4" class="dropMenu">
  
  <li><a href="/a/xinwendongtai/gongsixinwen/">公司新闻</a></li>
  
  <li><a href="/a/xinwendongtai/xingyexinwen/">行业新闻</a></li>
  
</ul><ul id="dropmenu5" class="dropMenu">
  
</ul><ul id="dropmenu6" class="dropMenu">
  
</ul><ul id="dropmenu7" class="dropMenu">
  
</ul><ul id="dropmenu8" class="dropMenu">
  
</ul>