<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'6LWE6LSo6I2j6KqJ');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[4]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[5]=array(0,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[6]=array(0,1,1,'6ZSA5ZSu572R57uc');
$cfg_Cs[7]=array(0,1,1,'5Lq65Yqb6LWE5rqQ');
$cfg_Cs[8]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[9]=array(4,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[10]=array(4,1,1,'6KGM5Lia5paw6Ze7');
?>