<li>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td width="10"><img src="/templets/default/images/p.png" alt=""/></td>
                            <td align="left"><a href="[field:arcurl/]">[field:title/]</a></td>
                            <td width="75">[field:pubdate function=strftime('%Y-%m-%d',@me)/]</td>
                          </tr>
                        </table>
                      </li>