<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",4,158);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",176,193);
$z[2]=Array("arcurl","",208,223);
$z[3]=Array("title","",239,253);
$z[4]=Array("pubdate","",302,348);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",373,387);
$z[6]=Array("description","",427,447);

?>