<?php
$z[0]=Array("channelartlist","\r\n<ul id=\"dropmenu{dede:field.typeid/}\" class=\"dropMenu\">\r\n  {dede:channel type='son' noself='yes'}\r\n  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n  {/dede:channel}\r\n</ul>\r\n",1,271);
$z[0][4]['typeid']="top";
$z[0][4]['cacheid']="channelsonlist";
$z[1]=Array("global","",432,456);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",468,494);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("flink","[field:link /]",565,628);
$z[3][4]['type']="textall";
$z[3][4]['row']="24";
$z[4]=Array("global","",651,683);
$z[4][4]['name']="cfg_templets_skin";

?>