<?php
$z[0]=Array("global","",58,83);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",747,773);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",1113,1141);
$z[2][4]['name']="cfg_memberurl";
$z[3]=Array("global","",1518,1545);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",1618,1645);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1648,1675);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("channel","\r\n    <li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a><span>|</span> </li>\r\n    ",1833,2085);
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a><span>|</span></li>";
$z[7]=Array("global","",2341,2373);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",2498,2530);
$z[8][4]['name']="cfg_templets_skin";

?>